### PR TITLE
[daily-stable10] run smoketests before publishing 

### PR DESCRIPTION
**Pull request by patrickjahns**

### CODE REVIEW

**Comment by tboerger** [comment]
I'm not sure if we should really do the whole smoke testing for daily unstable builds.

**Comment by patrickjahns** [comment]
I've wanted to do that to avoid publishing broken containers ... up 2 you

**Comment by tboerger** [comment]
Yeah but if it's missing a daily build there had been even complains about it. I get your intention. It makes sense to push only working images... Maybe we could run some tiny smoketest? I would not run the entire suite for nightly builds.

**Comment by patrickjahns** [comment]
> Maybe we could run some tiny smoketest? I would not run the entire suite for nightly builds.

Maybe we go back to the simple curl approach here?

**Comment by tboerger** [comment]
Let's delay that until 1.0.0 with the proper service setup.

**Comment by tboerger** [comment]
Let's delay the daily smoketests...

**Pull request closed without merging**
