### PR TITLE
Feature play with docker

### PR DESCRIPTION
**Pull request by patrickjahns**
# Motivation

provide an easy way to startup the docker containers for a test spin

test it 
[Try in PWD](http://play-with-docker.com?stack=https://raw.githubusercontent.com/owncloud-docker/server/feature_play_with_docker/docker-compose.yml)

### CODE REVIEW

**Comment by patrickjahns** [comment]
```
unsupported Compose file version: 2.1
```
-_- - will bump the version later

**Comment by tboerger** [comment]
> -_- - will bump the version later

we set this low version intentional because people on older systems complained about it.

**Comment by tboerger** [comment]
Just tried this button, PWD doesn't support the default variable assignment :)

**Comment by tboerger** [comment]
Closing as the docker-compose config gets removed from this repo.

**Pull request closed without merging**
