### PR TITLE
Initialize drone integration

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey Thomas, does this change come with upgrade instructions?

**Comment by tboerger** [comment]
The images should stay like they are from the functionality, just the process how they are getting built and barely tested changed. Need to check it tomorrow, but maybe it's also possible to prepare some kind of feed for you and the community to see if something changed.

**Comment by ThomDietrich** [comment]
That would be good (see #19 😉 )

Imho one problem with docker based solutions is, that you trade administrative work for trust in the person maintaining the docker solution. I fear that one day my setup will just not work any longer because of incompatible changes and my lack of knowledge about them. A changelog and some upgrade instructions provided with them would be a big help here.

**Comment by tboerger** [comment]
I'm currently also migrating the base image to drone, I think I will start writing a changelog there since it got nearly all moving parts

**Pull request merged**
