### PR TITLE
Release 10.5.0 RC2

### PR DESCRIPTION
**Pull request by HanaGemela**

### CODE REVIEW

**Comment by jnweiger** [comment]
The ci fails with 
* test-arm32v7-latest: Error: No such image: docker.io/owncloud/ubuntu:latest
  @phil-davis is that trying to pull an ubuntu-20.04 based arm32 image? -- It does not exist. If so, we must exclude that. 
* There is also a weird redis error about THP and other settings being applied in what they say the wrong order.

I cannot tell why we get these failures now, but did not get them with beta2.

**Comment by phil-davis** [comment]
@jnweiger yes, arm32 does not exist in the set of Ubuntu 20.04 images. So that needs to be removed.

**Comment by jnweiger** [comment]
@micbar  @phil-davis we are blocked here. The CI hits the 1h timeout of drone. 
Should we merge and hope that we can trigger one successful build during the weekend?

**Comment by micbar** [comment]
> @micbar @phil-davis @dschmidt we are blocked here. The CI hits the 1h timeout of drone.
> Should we merge and hope that we can trigger one successful build during the weekend?

Can we boil that down to a particular test suite?

Or is it possible to split the tests? I remember that there is some magic in the drone.star to split the acceptance tests based on configurable number of chunks. @phil-davis

**Comment by micbar** [comment]
Could we just use 4 here ? https://github.com/owncloud-docker/server/blob/master/.drone.star#L51

**Comment by phil-davis** [comment]
> Could we just use 4 here ? https://github.com/owncloud-docker/server/blob/master/.drone.star#L51

Yes, in the end that causes:
https://cloud.drone.io/owncloud-docker/server/126/2/9

`bash tests/acceptance/run.sh --remote --tags "@smokeTest&&~@skip&&~@skipOnDockerContainerTesting" --type api --part 1 3`

And `run.sh` knows how to count the number of API test suites, and splits them up, e.g. if there are 24 suites, then 8 per pipeline, If we split into 4 parts, then 6 per pipeline.

We might run into some concurrent job limit on cloud.drone.io and some pipelines will wait to start, but that is better than getting a timeout.

**Comment by micbar** [comment]
@jw @phil-davis let us see how it behaves.

**Pull request merged**
