### PR TITLE
build: add 10.13.4

### PR DESCRIPTION
**Pull request by jnweiger**

### CODE REVIEW

**Review by xoxys — CHANGES_REQUESTED** [review]
New config option to suppress ioc not implemented.

**Comment by jnweiger** [comment]
Implemented in https://github.com/owncloud-docker/base/pull/321

**Comment by TheRealBro** [comment]
Merged PR to base container, although I have to say the implementation of this feature is quite bad. Asking a config value (which might be compromised by an attacker) to show a security warning or not at update is maybe not the best idea. Plus it adds way more overhead in deployments. I would ask to revert this and start from scratch rethinking the design of this "Warning", but that's above my paygrade. For here, we at least documented it and can disable the warning in automated deployments.

**Review by xoxys — APPROVED** [review]

**Comment by jnweiger** [comment]
> Merged PR to base container, although I have to say the implementation of this feature is quite bad. Asking a config value (which might be compromised by an attacker) to show a security warning or not at update is maybe not the best idea. Plus it adds way more overhead in deployments. I would ask to revert this and start from scratch rethinking the design of this "Warning", but that's above my paygrade. For here, we at least documented it and can disable the warning in automated deployments.

Good thinking! 
I've thought about that briefly, but quickly (maybe too quickly) dismissed concerns: an attacker who can edit config.php has probably already enough edit power to remove anything from the admin UI that he wants to remove.

**Pull request merged**
