### PR TITLE
Release 10.13.0-rc.1

### PR DESCRIPTION
**Pull request by jnweiger**
Add release candidate 1 for core 10.13.0 to the docker config.

### CODE REVIEW

**Comment by xoxys** [comment]
Please use the commit message body for additional descriptions not the title.

**Comment by jnweiger** [comment]
Added a description body, but honestly this PR is trivial and obvious, and I don't know what 'additional description' should be there.

**Comment by xoxys** [comment]
There doesnt need to be anything in the body. Just dont add stuff like "qa is done lets add an rc now" to the title please.

**Comment by jnweiger** [comment]
Sorry, I wish I cloud remember half the rules, that apply here.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
