### PR TITLE
bump 10.11.0 from rc.1 to rc.2

### PR DESCRIPTION
**Pull request by jnweiger**
... and later tonight we'll have the final!

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud-docker/server/1355/2/6
complains about `gomplate` - what does that have to do with an Apache+PHP application?

@xoxys

**Comment by xoxys** [comment]
Rebase to master is missing. @jw you are on an outdated state.

**Comment by xoxys** [comment]
Ah no wait the PR to update the image chain below is not merged yet.

**Comment by xoxys** [comment]
Merged. Should be fixed on this PR as well after a rebase.

**Pull request merged**
