### PR TITLE
release 10.10.0 rc1

### PR DESCRIPTION
**Pull request by jnweiger**
10.10.0-rc1 is complete-20220504

### CODE REVIEW

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud-docker/server/1268/2/6

what is this Trivy stuff about?

**Comment by xoxys** [comment]
Gomplate can be added to the ignorefile https://github.com/hairyhenderson/gomplate/issues/1352#issuecomment-1110704777

The rest need to be checked and fixed or ignored as well: https://aquasecurity.github.io/trivy/v0.27.1/docs/secret/scanning/

**Comment by jnweiger** [comment]
Puh. It seems trivy prevents us from building the image, so I cannot debug the situation.
@xoxys do you know a way how to build this locally?

**Comment by jnweiger** [comment]
I've added the gomplate cve to .trivyignore.
@C0rby can you give advise for the rest?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
> we now have two explosions in the tests.

The `files_external` app is disabled by default, so I skipped those tests - like we did in core when that change came. I could also add a pipeline that enables the `files_external` app and runs those tests. Is that worth doing?

**Review by xoxys — APPROVED** [review]

**Comment by xoxys** [comment]
> > we now have two explosions in the tests.
> 
> The `files_external` app is disabled by default, so I skipped those tests - like we did in core when that change came. I could also add a pipeline that enables the `files_external` app and runs those tests. Is that worth doing?

I guess that's related for appliance and QNAP as well, as those repos are running the test suite as well. Could you take a look and create PR?

**Comment by phil-davis** [comment]
> I guess that's related for appliance and QNAP as well, as those repos are running the test suite as well. Could you take a look and create PR?

@xoxys or @jnweiger Can you give links to those please?

(and I can check what tests they do in CI)

**Comment by xoxys** [comment]
https://github.com/owncloud-docker/appliance
https://github.com/owncloud-docker/qnap

Thanks

**Pull request merged**
