### PR TITLE
Release 10.5.0 RC4

### PR DESCRIPTION
**Pull request by phil-davis**
Notes:
- the grace period popup should be disabled by default in all acceptance tests now, so that extra commit should no longer be needed here.
- maybe the "disable theme-enterprise" commit is also no longer needed?

### CODE REVIEW

**Comment by phil-davis** [comment]
https://cloud.drone.io/owncloud-docker/server/157/14/1

The pipeline prepublish-arm64v8-10.5.0-rc4 looks like it ran OK and pushed a docker image b1d2e716130f077f3587708a325daa07279486e6-10.5.0-rc4-arm64v8 - but the test-arm64v8-10.5.0-rc4 pipeline server step claims to be pulling it, but it does not arrive in time (not in 10 minutes, and not in 20 minutes in other PRs)

**Comment by phil-davis** [comment]
"just for fun" I tried enabling the arm32 n Ubuntu 20.04. But that fails with "manifest for owncloud/base:20.04-arm32v7 not found: manifest unknown: manifest unknown" - I guess the "upstream" owncloud/base owncloud/php etc do not have that image either, so there is no way to try that here.

**Comment by jnweiger** [comment]
> "just for fun" I tried enabling the arm32 n Ubuntu 20.04. But that fails with "manifest for owncloud/base:20.04-arm32v7 not found: manifest unknown: manifest unknown" - I guess the "upstream" owncloud/base owncloud/php etc do not have that image either, so there is no way to try that here.

Yes, the upstream ubuntu:20.04 image for arm32 does not exist. Not much we can do about that, except for retrying every now and then. Do we have a usecase for arm32?

**Comment by phil-davis** [comment]
> Do we have a usecase for arm32?

Maybe "old" RaspberryPi at home. I don't think any data-centre-based cloud storage is going to have 32-bit CPUs of any architecture any more!

For the moment we don't worry about it for 10.5.0RC4. But somebody will need to decide if this owncloud-docker/server is to have any 32-bit images released for 10.5.0 final.

**Comment by jnweiger** [comment]
> https://cloud.drone.io/owncloud-docker/server/157/14/1
> 
> The pipeline prepublish-arm64v8-10.5.0-rc4 looks like it ran OK and pushed a docker image [b1d2e71](https://github.com/owncloud-docker/server/commit/b1d2e716130f077f3587708a325daa07279486e6)-10.5.0-rc4-arm64v8 - but the test-arm64v8-10.5.0-rc4 pipeline server step claims to be pulling it, but it does not arrive in time (not in 10 minutes, and not in 30 minutes). I guess it will never come.
> 
> Why is it so?

The world changed. To verify that we did not break it, I took the last successful run https://cloud.drone.io/owncloud-docker/server/148 and retriggered it as https://cloud.drone.io/owncloud-docker/server/164 it now fails at the same test-arm64v8 step.

**Comment by phil-davis** [comment]
It blocks ARM docker images (32-bit were already blocked, and 64-bit are now also blocked).
We could go ahead without any ARM images.

**Comment by jnweiger** [comment]
> It blocks ARM docker images (32-bit were already blocked, and 64-bit are now also blocked).
> We could go ahead without any ARM images.

Improvement idea:
* Disentangle the pipelines regarding platforms: so that amd84 can succeed when armXX is broken. (currently both ARM's are broken)
* Disentangle the pipelines regarding versions: so that 10.5.x can succeed when 10.4.x is broken. (Not currently the case).

@xoxys @micbar @dschmidt drone experts: is this technically feasable or desirable with drone?

**Comment by xoxys** [comment]
> @xoxys @micbar @dschmidt drone experts: is this technically feasable or desirable with drone?

Technically possible, but:
- adds more complexity
- nobody will care about broken images if we don't enforce pipelines to pass

Ideas:
- if something is really broken, disable it in the drone pipeline
- everything active pipeline step should be enforced to pass, always

**Comment by micbar** [comment]
> everything active pipeline step should be enforced to pass, always

Same opinion.

**Comment by phil-davis** [comment]
So for now, if we can't see how to fox the arm64 image, then we remove it from the drone pipelines.

**Comment by xoxys** [comment]
Fixed. Issue was related to the drone cache registry.

**Comment by jnweiger** [comment]
Robert for president!
What the heck is a drone cache registry?

**Comment by xoxys** [comment]
We are running a docker registry beside drone which is used for the prepublishing steps and cachinge the image during the drone run. It's a temp cache registry and will be cleaned up automatically

**Comment by phil-davis** [comment]
So we need to ask sysadmin sooner when we get "mystery" fails. We could have spent a month trying to search for all sorts of bugs in Ubuntu 20.04 or one of the chain of owncloud docker images that lead up to this server image.

Do we even see this temp cache registry mentioned anywhere in the drone or other scripts of this repo?
Or is it completely transparent, and so we really have no hope to know it is even there?

**Comment by phil-davis** [comment]
@jnweiger I rebased/squashed into the 5 commits here that seemed logical to me. CI passes.

Maybe you could cleanup the commits in #192 in a similar way? And then it can be merged.

**Comment by xoxys** [comment]
> Do we even see this temp cache registry mentioned anywhere in the drone or other scripts of this repo?
> Or is it completely transparent, and so we really have no hope to know it is even there?

https://github.com/owncloud-docker/server/blob/master/.drone.star#L564 You were right with your idea that the prepublished image was somehow damaged but it's hard to verify this in the drone log. A good indicator for a registry issue is https://cloud.drone.io/owncloud-docker/server/165/14/1. If you see "Pulling from ..." output twice, something seems to be wrong with the registry.

**Pull request merged**
