### PR TITLE
Add 10.15.0 rc.4

### PR DESCRIPTION
**Pull request by jnweiger**
rc.4 should fix the trivy issues seen yesterday with rc.3

### CODE REVIEW

**Comment by jnweiger** [comment]
@phil-davis I need some advise here:
.drone star used to rebuild all the old releases 10.14.0 and 10.13.4 togeher with the nw release that I actually want.
Out security updates phpseclib 3.0.39 etc... now work nicely for my new 10.15.0-rc.4 build target. 
But (of course), they don't work for 10.14.0 or 10.13.4

Is it fine to leave these two behind as they are, and only build 10.15.x from now on?

**Comment by phil-davis** [comment]
> Is it fine to leave these two behind as they are, and only build 10.15.x from now on?

I think so. Actually we shouldn't be rebuilding the old releases over-and-over - they should stay as they are, and not have the build date keep getting touched.

**Comment by jnweiger** [comment]
One argument for rebuilding them over and over again was (security) updates going into base images.
(But imho not incrementing any digits in the version number spoiles all that anyway.)

**Comment by phil-davis** [comment]
> One argument for rebuilding them over and over again was (security) updates going into base images.

True, there could be components of the OS base and tools/libraries that get out-of-date and are missing new security patches.

**Pull request merged**
