### PR TITLE
ci: use daily qa by default

### PR DESCRIPTION
**Pull request by xoxys**

### CODE REVIEW

**Comment by xoxys** [comment]
@phil-davis Can you take a look on this? Some tests failing with the daily QA tarball even if the skip tags seem to be used, e.g.

```
Running apiAuth tests tagged ~@skipWhenTestingRemoteSystems&&~@skipOnOcV10&&~@skipOnOcV10.10&&~@skipOnOcV10.10.0&&@smokeTest&&~@skip&&~@skipOnDockerContainerTesting&&@api 
```

**Comment by xoxys** [comment]
Thanks. Old `composer.json` was the issue :+1:

**Review by phil-davis — APPROVED** [review]

**Comment by xoxys** [comment]
@phil-davis Why have you reverted my last commit?

**Comment by phil-davis** [comment]
I just squashed the commits. Sorry, I didn't see that you pushed anything in the last minutes.

**Comment by xoxys** [comment]
Yes, a small one to allow overwriting the behat composer url.

**Comment by phil-davis** [comment]
This is the challenge of syncing when multiple people work on a branch. I got home after being out for a while, saw green CI, and so I just locally squashed a bunch of commits to clean things up and force-pushed.

I should have checked first to see if anything else had happened that was not in my local branch - sorry.

**Comment by xoxys** [comment]
No worries, not a big deal and yes working in the same branch is always a bit challenging.

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
