### PR TITLE
[DO NOT MERGE] build: add rc.3 docker

### PR DESCRIPTION
**Pull request by jnweiger**

### CODE REVIEW

**Comment by phil-davis** [comment]
tag: v10.15.0-rc.3 does not have the commit for "[10.15.0] chore(deps): bump phpseclib/phpseclib from 3.0.38 to 3.0.39 (#41276)" in it.

Maybe that is why Trivy is complaining?

**Comment by phil-davis** [comment]
We need updated PHP dependencies for files_external_dropbox
https://github.com/owncloud/files_external_dropbox/pull/161

To fix the Trivy messages about `guzzlehttp/psr7`

**Comment by phil-davis** [comment]
And similar for:
https://github.com/owncloud/openidconnect/pull/314

I think that releases will need to be done for those 2 apps, so that a version of them with up-to-date dependencies can be bundled with 10.15.0

**Comment by jnweiger** [comment]
> tag: v10.15.0-rc.3 does not have the commit for "[10.15.0] chore(deps): bump phpseclib/phpseclib from 3.0.38 to 3.0.39 (#41276)" in it.

Scrap that!  That tag was off by one. I keep doing that all the time. :see_no_evil: )
I'l rebuild 10.15.0-rc.3 inplace to save the hassleof a new config.

**Comment by jnweiger** [comment]
Thanks @phil-davis for those updates, 
* the tag for rc.3 was off by one. ( I keep doing this all the time :see_no_evil: )
* will make releases for dropbox and openidconnect
* then we'll call it RC 4

**Comment by phil-davis** [comment]
@jnweiger this is out-of-date since PR #488 

close?

**Pull request closed without merging**
