### PR TITLE
update to 10.9.1 final

### PR DESCRIPTION
**Pull request by jnweiger**
We now build 10.9.1, 10.9.0 and 10.8.0 here.

Should we remove one of the old ones here? 
 Not sure, if I understand the confluence page correctly, it seems to say that 10.9.0 should go.

### CODE REVIEW

**Comment by xoxys** [comment]
IMO the `10.9.0` block needs to stay to get e.g. OS updates published to `10.9.0`.

**Review by xoxys — CHANGES_REQUESTED** [review]
Before we forget about it, please add it to the tag list in the readme.

**Review by phil-davis — APPROVED** [review]

**Review by xoxys — APPROVED** [review]

**Comment by xoxys** [comment]
@jnweiger please merge if you are ready

**Comment by jnweiger** [comment]
> @jnweiger please merge if you are ready

I was only  waiting for the pipelines to finish...

**Pull request merged**
